import { fetchRedis } from "@/lib/hepper/redis";
import React, { Suspense } from "react";
import { Metadata } from "next";
import { Servers } from "@/types/servers";
import Loading from "@/components/chat/loading";
import GroupChatLayout from "./group-chat-layout";
import { GroupMessage } from "@/types/group-message";
import { groupMessageArrayValidator } from "@/lib/validation/group-message";
import { auth } from "@clerk/nextjs/server";
import { UserData } from "@/types/user";

interface PageProps {
  params: Promise<{
    serverId: string;
  }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { serverId } = await params;

  try {
    const data = await fetchRedis("get", `servers:${serverId}`);

    if (!data) {
      return {
        title: "Server Not Found",
        description: "The requested server does not exist",
      };
    }

    const serverData = JSON.parse(data);

    return {
      title: `Chat room ${serverData.serverName}`,
      description: "Generated by Cmanh",
    };
  } catch {
    return {
      title: "Server Error",
      description: "Failed to load server information",
    };
  }
}
async function getChatMessages(serverId: string) {
  try {
    const result = (await fetchRedis(
      "zrevrange",
      `servers:${serverId}:messages`,
      0,
      19
    )) as string[];
    const dbMessages = result.map(
      (message) => JSON.parse(message) as GroupMessage
    );

    const messages = groupMessageArrayValidator.parse(dbMessages);
    return messages.reverse();
  } catch {
    return [];
  }
}
const Page = async ({ params }: PageProps) => {
  const { userId } = await auth();
  if (!userId) {
    return (
      <div>
        <p>Please sign in</p>
      </div>
    );
  }

  const { serverId } = await params;
  // check user is member of the server
  const membersRaw = (await fetchRedis(
    "smembers",
    `servers:${serverId}:members`
  )) as string[];
  console.log("members", membersRaw);
  if (!membersRaw) {
    return (
      <div>
        <h1>Error to get server data</h1>
      </div>
    );
  }
  const members = membersRaw.map((member) => JSON.parse(member) as UserData);
  const isMember = members.find((member) => member.id === userId);
  if (!isMember) {
    return (
      <div>
        <h1>Access Denied</h1>
      </div>
    );
  }

  const data = await fetchRedis("get", `servers:${serverId}`);

  if (!data) {
    return (
      <div>
        <h1>Server Not Found</h1>
        <p>The server with ID {serverId} does not exist.</p>
      </div>
    );
  }

  const serverData = JSON.parse(data) as Servers;
  const initialMessages = (await getChatMessages(serverId)) as GroupMessage[];

  // handle if not a member in server can't access

  return (
    <Suspense fallback={<Loading />}>
      <GroupChatLayout
        serverId={serverId}
        serverData={serverData}
        initialMessages={initialMessages}
        members={members}
      />
    </Suspense>
  );
};

export default Page;
