import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ClientProvider from "./client";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { fetchRedis } from "@/lib/hepper/redis";
import { getFriendsByUserId } from "@/lib/hepper/get-friends";
import { getCachedFriendRequests } from "@/lib/cache/friend-requests";
import { Message } from "@/types/message";
import PusherDebug from "@/components/pusher-debug";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  if (!user) {
    return (
      <div>
        <p>Please sign in</p>
      </div>
    );
  }
  const unseenRequests = (await fetchRedis(
    "smembers",
    `user:${user.id}:incoming_friend_requests`
  )) as string[];

  const initialFriends = await getFriendsByUserId(user.id);

  const friendsWithLastMessage = await Promise.all(
    initialFriends.map(async (friend) => {
      const sortedIds = [user.id, friend.id].sort();
      const [lastMessageRaw] = await fetchRedis(
        "zrange",
        `chat:${sortedIds[0]}--${sortedIds[1]}:messages`,
        -1,
        -1
      );
      if (!lastMessageRaw) {
        return {
          ...friend,
          lastMessage: {
            id: "",
            text: "You are now friends! Let's chat together.",
            senderId: "",
            timestamp: 0,
          } as Message,
        };
      } else {
        const lastMessage = JSON.parse(lastMessageRaw) as Message;
        return {
          ...friend,
          lastMessage,
        };
      }
    })
  );

  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        </ThemeProvider> */}
          <ClientProvider
            unseenRequestCount={unseenRequests.length}
            initialFriends={friendsWithLastMessage}
            userId={user.id}
          >
            {children}
          </ClientProvider>
          <Toaster richColors position="top-center" closeButton />
          <PusherDebug />
        </body>
      </html>
    </ClerkProvider>
  );
}
